### ISSUE TITLE
Adding few styles into window

### ISSUE THREAD

**Issue by Phoro92** [PapeCoding/kanboard-CustomUserCSS#1]
I was trying to add few styles using your plugin but got this error after i am trying to save this:

```
#tooltip-container {width: 35%;}
.task-form-bottom {
	margin-top: -3%;
	width: 300px;}
.form-actions {
	padding: 0;}
.task-board { 
    margin-bottom: 4px;
    padding: 8px;
    border-radius: 3px;
    border: none;
    border-radius: 3px;
    border-bottom: none;}
```

Internal Error: SQL Error: SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(255)

**Comment by PapeCoding** [comment]
Oh, apparently the storage I used to store the CSS data is limited to 255 characters.
Unfortunately right now I have not enough experience nor time to add a correct data base model to fix this issue. If someone else is willing to implement this with a custom table, I would be happy to merge it.

@korlikiangel As a workaround for you right now: You CSS seems quite redundant. Is that needed to exploit some kind of quirk in CSS or would the following (< 250 characters) also work?
```css
#tooltip-container {width: 35%;}
.task-form-bottom {
	margin-top: -3%;
	width: 300px;}
.form-actions {
	padding: 0;}
.task-board { 
    margin-bottom: 4px;
    padding: 8px;
    border-radius: 3px;
    border: none;}
```
